/*
--- Day 1: Trebuchet?! ---

Something is wrong with global snow production, and you've been selected to take a look. The Elves have even given you a map; on it, they've used stars to mark the top fifty locations that are likely to be having problems.

You've been doing this long enough to know that to restore snow operations, you need to check all fifty stars by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

You try to ask why they can't just use a weather machine ("not powerful enough") and where they're even sending you ("the sky") and why your map looks mostly blank ("you sure ask a lot of questions") and hang on did you just say the sky ("of course, where do you think snow comes from") when you realize that the Elves are already loading you into a trebuchet ("please hold still, we need to strap you in").

As they're making the final adjustments, they discover that their calibration document (your puzzle input) has been amended by a very young Elf who was apparently just excited to show off her art skills. Consequently, the Elves are having trouble reading the values on the document.

The newly-improved calibration document consists of lines of text; each line originally contained a specific calibration value that the Elves now need to recover. On each line, the calibration value can be found by combining the first digit and the last digit (in that order) to form a single two-digit number.

For example:

1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet

In this example, the calibration values of these four lines are 12, 38, 15, and 77. Adding these together produces 142.

Consider your entire calibration document. What is the sum of all of the calibration values?
*/

    fun main() {
        println("Day1")

        day1partA(input)
    }

val testinput = "1abc2\n" +
        "pqr3stu8vwx\n" +
        "a1b2c3d4e5f\n" +
        "treb7uchet"

val input = "gsjgklneight6zqfz\n" +
        "7one718onegfqtdbtxfcmd\n" +
        "xvtfhkm8c9\n" +
        "914two8\n" +
        "vxzzvdhfqfsix83c1ttvbbstxgdrkfcnmm3\n" +
        "76mkvhmbkpm\n" +
        "8sixssmlzlhrnineggmrvg6\n" +
        "threeninedtr7219\n" +
        "two2geight\n" +
        "3nine9fivetwo9twohxhc8\n" +
        "llbfmnzzntdcfbslcl3xxvz\n" +
        "two3leighttvpkfmjhhonefour\n" +
        "1b9four\n" +
        "fivefdlqonesj2six\n" +
        "hfptgztwosix8\n" +
        "fourkcxqfgxbsvjj3472\n" +
        "xhzs7rdphtxhtwo\n" +
        "eightthree51\n" +
        "3nmronemlqzfxgonepkh\n" +
        "9vnxqtjjrsg\n" +
        "533fivesixrvqfxjrdhl\n" +
        "bkrljtkjb42fqnp\n" +
        "4mrh734\n" +
        "threefourfive83l\n" +
        "lcjftnpqfourfivesixtwof3\n" +
        "sevennineh7two3\n" +
        "onecgrmb74ctxhg\n" +
        "kmvtdrxvrfivethree2\n" +
        "seven98mflv\n" +
        "tmoneightzstdjqjncnkpkknzoneonethreefive7\n" +
        "fourzsqjbffmxf6lsqdttjfive1nine\n" +
        "ccs3onesgmmrb\n" +
        "kflkpscthreehjjgckfrfdhc3krgntwofour\n" +
        "7five2134\n" +
        "pnfbrjhgprdsvzjrklrclmlgkk69four4\n" +
        "cheightwofourxt2\n" +
        "1167threetfqstpkc\n" +
        "6dsk2bhqmonejggkpvffhgnrbsix\n" +
        "five9threefour\n" +
        "one3136four\n" +
        "vvncdsg6jnxlbsb3\n" +
        "fgftp5\n" +
        "xxscpztpxteightv4mprlzmdhxtxmpvgfour\n" +
        "g4\n" +
        "eightmbqbrxjbdx5\n" +
        "8nineeighttwo6lcsvmvxdqbgpdbtjnnine\n" +
        "jkj86threeskgpnl3four\n" +
        "rtmpn5cbtthreefgxnhhvlkxcbtknnine\n" +
        "7dpn6cqstqrv7sbgzxhgrqrgn\n" +
        "3fivetxgjgndz1\n" +
        "tfmkd8three2\n" +
        "rcl55cvnfour9twofive\n" +
        "dmgdbkfjvsnpctj69four5\n" +
        "xjlrvznbgl78eight\n" +
        "dmhkvgbc6four6eightwofkk\n" +
        "zlhzn898scffour\n" +
        "bdeighttxntvnslbf1nine59\n" +
        "htjltzmzeight5foureightdvv\n" +
        "45fourl2\n" +
        "seventhree39fivesixtwokchzgc\n" +
        "fxtbgsxch1lmdsldthreefour8rkxjz9\n" +
        "five3five8\n" +
        "threefvfcxnfgskqjdjknrgkvnkl6\n" +
        "8jzdkxm\n" +
        "plttwo2fourseven99zthrklvcvp\n" +
        "gxjfdnzrcj2847eightnine\n" +
        "2onetwoxdc\n" +
        "35zlpzpvfn77\n" +
        "nxppmskvrd1one89eightfive\n" +
        "glhp52f\n" +
        "mpptktkhrbbcsdheighteightqkjgckvxs6fourseven\n" +
        "1ninelspvpm\n" +
        "threefqn551\n" +
        "eight95lhxrtwoh2hbnd\n" +
        "jlbclhxp72fivektxfxbtwonetxl\n" +
        "one7nflzdbdjchbbqqmn\n" +
        "fivesbgsrvzrhz2ncbkhsbrgnpbkgcsrln1zksfqkcxpf\n" +
        "1ftfour22hvdcqrseven\n" +
        "sevenjgrkpbxxnnv1nine6hzkrzzfl\n" +
        "fourthreefour98sevenbthreesix\n" +
        "sixgrrjkl3gdzz86onejpjlbpnthree\n" +
        "vhx3tnzcjvgg\n" +
        "six3one4sixeighttwosbkqdjfhfroneights\n" +
        "669eighteight32seven\n" +
        "jdpzkdnngc6bvqvtxtxfivesixthreedndsqmv\n" +
        "9eight6ssxcdt6fivedsnine\n" +
        "nine3onetjmdqpktwo\n" +
        "ninejjzrklhptsdzbt6tmxnpbrm\n" +
        "eightsevensixtxvxlqtdjfivebnvpdhvfsqbbssfkplzmkvvxh7\n" +
        "xmeightone5cjgn1nhjsthree5\n" +
        "xncbclzqqgskthree14bptlrknkmpntxmnf\n" +
        "sevenfour8\n" +
        "34\n" +
        "5ccslrvbfive\n" +
        "sixsixlqf72\n" +
        "kknmskkfivezcmjrgfgclgrz1\n" +
        "gqxtmrsqxfour12vlonefive\n" +
        "four8594kxsc\n" +
        "364\n" +
        "hrbfxdpfivesevenjcjdm3nine9sixsh\n" +
        "mml5five\n" +
        "btcqdx7jjsix\n" +
        "4558seven4mjzsix\n" +
        "1mfckqcfk\n" +
        "4pjtbd18ghnnjqmjm6cvcdgjlcrmxpnnts\n" +
        "eight6hd\n" +
        "cdjdhpjccncpmrfour9qxlqfivenxjfssftnq\n" +
        "5bchcbpjxnsbkxgbqgbr\n" +
        "sixlhnzzmkbfourhzp58onetwoseven\n" +
        "kfgkqfivek3br\n" +
        "fnklssmgnine4eight\n" +
        "rbbnjvgpkgbs65sevenmeightsevennine\n" +
        "8ninenzgpldnfgjjmbqpmqvgqcthree5seven2\n" +
        "seven6pdrgrldhtldhmndbjpj\n" +
        "5three4zmjpslhh\n" +
        "threesixsix45\n" +
        "szxnvzrkseven2tctf\n" +
        "xqzpninesixseven5dndlqd7\n" +
        "three6ghhzcvpkfivervsgplxq\n" +
        "eighttwoeightlfntmxptgk2pngplvr39\n" +
        "33ninenine4fivejseven6\n" +
        "fivehxbmjvxxrzrqr29npqhhlsjr2ttmnl\n" +
        "slmltqplzl73dxkxrpgn\n" +
        "lxg4371three\n" +
        "tjxsmjnthreefive5fivemshrhhj\n" +
        "5eighttwo\n" +
        "sixbpqtcrjzmveighteightjzgktzss1\n" +
        "1qxjz57sixzh\n" +
        "4djpqz54122\n" +
        "threeclg1ng7kgprvd\n" +
        "3143threenine71\n" +
        "kcxmcthreesixeight23\n" +
        "4zhvn4five\n" +
        "lmxfone47fbdsixjgl\n" +
        "kzcdzp2\n" +
        "27twozjbtr\n" +
        "gpvkqdpbpzthreeone5\n" +
        "bqvneightseven8qll\n" +
        "seven8brjrp272none\n" +
        "3kxhglddkjklkl\n" +
        "5sevennine52nine\n" +
        "3fourgznkfpfsxzsnmoneqsixtsm\n" +
        "twothreemkz6ttrtbj8\n" +
        "qoneight28fourninempvltzrtzgvfdcdlxv\n" +
        "rllmkpvgqnkdgdrseven2five3\n" +
        "7eight89fourlkfourfivejkqgffz\n" +
        "four6xr\n" +
        "6sixfive2hhzdkskxnine3nine\n" +
        "two6qmmkhb9eight\n" +
        "cqfxnmrlnhcsdqqxkn2nsncgvdxgmnineeight\n" +
        "7sixsdsfour4mrxeight\n" +
        "44threetcmtzmxzgjonesixnine8seven\n" +
        "dlonethreejh6bgxxmlkdseightwokp\n" +
        "four3lspkhhtsmone\n" +
        "89hjtnrrpvfzjdkzp\n" +
        "xc4sixvzpccdblczvleight7\n" +
        "2twotwogzqhp9vnbp\n" +
        "rxsplmvb1two8pdtnxtbthreefiveeight\n" +
        "bsfdmnnj8eight\n" +
        "rntszdckhhcmqn21ljzqbhn\n" +
        "nineeight8\n" +
        "1fhmnzzlfjpdp3ptj8threejqvmstbtp\n" +
        "267\n" +
        "hkknsfivecrhthvbhhqj1\n" +
        "six6xcqpnj9fivezcqbrfour4\n" +
        "8one2gfsgg\n" +
        "mszrrqmr4nine9\n" +
        "5fournine43three\n" +
        "5one9hvvrthreethreef3\n" +
        "ninetwo6twofivefivennhjqkhzntkqptfxvdj\n" +
        "9onetwo5fiveeightnine8\n" +
        "nineseventslmmgnsjbdgsb2sixlmvxpdg6\n" +
        "8nineonethreehghh\n" +
        "jd1kr\n" +
        "drrsxljl4\n" +
        "fqhfjdxdlsgjgkhcpjkqpgzjgchsixrvzqn7\n" +
        "7one2qsnxhfqkseven6\n" +
        "1vhljtwo1oneightqm\n" +
        "gl3\n" +
        "two2eight1threethree\n" +
        "64nine\n" +
        "qglkhnfffsnine2three566three\n" +
        "7sixtwo6trbbklgjteighttwo\n" +
        "nkccpeight4sevensevenone\n" +
        "eight9ldkvgqhq3\n" +
        "ttkqpxpzrxph1zfzhbvbgvn\n" +
        "46lqxxgrmvsix\n" +
        "twosixcqsmjsthree8pqthmd\n" +
        "ninesixdsns66lvnkhrq3\n" +
        "seven413crqjpkfqleightlgxgck\n" +
        "onesxztkrtxksqklpqcmrlpjlnst6ftwo\n" +
        "jzb1oneightqqr\n" +
        "ninexrmlglbdlfqm4twolnlq\n" +
        "4seven4eightzds\n" +
        "fourngdzkklkxtsix8\n" +
        "cggtwonebtkxtwothree16seven\n" +
        "three59threesix\n" +
        "3qfglrfcr4nine\n" +
        "9seveneighttwofoureightvvhpgmpnftwo\n" +
        "seven2sixvsmxv86\n" +
        "mgvqr5two\n" +
        "lggjffzt2six7vxflh23\n" +
        "hctpninesevenoneonevr3\n" +
        "7threeqzgzm532mn5\n" +
        "vltdnjhxgl6rjbmcb79s69eight\n" +
        "snkbpcgclpbflxbz6nkktqqgplm11bdnvpfour\n" +
        "75dllnlkthree93onedflbbmlvmd\n" +
        "sixthree94frdpkdccqkxv5\n" +
        "hdpsvxl2bszdpgspqgxrzz3\n" +
        "hztwonethreeeightzjqk8fivepvgrpsrxxsbfqfv\n" +
        "kfmh6sixv74two\n" +
        "one9three5\n" +
        "lcn2hls3three66gsfmzvlx\n" +
        "tmlhhl72nhhkppscc\n" +
        "eightsevenprzgonethree7nine1\n" +
        "1rngfnx78196sixrjbbkzp\n" +
        "6seven2182six\n" +
        "fpsl5xbdnjbzonethreezcfqmqonefive\n" +
        "5cxhrqzsfz34xdkvtxblkhvstcmjc\n" +
        "seven36ccqzfmmlvsevennine\n" +
        "5nrvq2nine2\n" +
        "fljzxvninetqxjjcrsvp7\n" +
        "1ninetwosevenvdtn4qcxnblgx2two\n" +
        "dcfxp2onefourfive\n" +
        "6czxzpsc\n" +
        "threeone1grvz8pvzvzkdzjfsix\n" +
        "hmbpnqntczjhdlsjonedr9prxvkt6one9\n" +
        "dccns9threeninexgflfjltmvlssrhkbvktcfourg\n" +
        "sevenhbflnmglrn4rtseventwo55\n" +
        "threehddkrvsp11\n" +
        "6threegtk5five\n" +
        "29m5\n" +
        "nine3threesixsevennineddgchfiveeightwovqq\n" +
        "2jtgvrldnbpfncfxtq\n" +
        "eighttwo6vtgkvpqzthree\n" +
        "5sixseven\n" +
        "twohj3seven3fourblqqbphcbfive\n" +
        "6one7twovjfqlsdgnrtzlzmjxgfljs\n" +
        "1nv\n" +
        "22five27two\n" +
        "3sevenlgeighteight\n" +
        "khpjmtsskfivefivexbjnkdtwogmxcxrqdpl2\n" +
        "zmvpjtm6gzgztjrtnmgpsevenfive28vjvhmnr\n" +
        "9four71\n" +
        "9zghgdjs\n" +
        "3oneqcjhsbv9threefive\n" +
        "47rsggonennqmbbckcdd31three\n" +
        "sevenfivesixone5eight\n" +
        "48hcmlcone8x6\n" +
        "three9threesixjtxhlm3eightgtrskhqfjtgfjbcfdt\n" +
        "5ninefrpqjdhkkcldvhqkljpqpb1\n" +
        "969nine\n" +
        "ninenine8ctprmxkvnine3xkl\n" +
        "seven648lpmxdn92\n" +
        "rjhvlnz5two\n" +
        "dlvqhfmp587\n" +
        "sevensix6\n" +
        "eightsix34fourlgxrndbjjx9mztwo\n" +
        "czlpflntvpc1qnl2\n" +
        "9seven8qsixbjoneeight\n" +
        "snnjcseventwo6qst\n" +
        "ndxgj756zqgt\n" +
        "krczgjpbfp199three4six\n" +
        "cjeightwoone8\n" +
        "ffmddcrh7rrxhpnlkkdl\n" +
        "nine9hhppdvfczxkjninefivecdp\n" +
        "8eight19\n" +
        "4fiveeightthree2twotwo\n" +
        "nine2four4941seven\n" +
        "fournine5twodqbkbjjmmqsn\n" +
        "nzqgngfxftwo6\n" +
        "5bmlfbsql2sevenjrxkkdtwoone\n" +
        "jfeightwoppxbpgzdljnmmpvrckv8\n" +
        "chj66fouronefourvcdd\n" +
        "fourzvgbsgkmgslntrzxtxvjnmhk5v7\n" +
        "1fnzftqmtj9gqkblpknq6blmlkxbzhdsdljvqfour\n" +
        "116rqpdqq\n" +
        "xslxqcmlchmqlzmkxbk79hnlhthreesnnmnht\n" +
        "sixfive8kjhrfdxrtfour\n" +
        "nlv71clmzbnine6\n" +
        "42one8lz\n" +
        "qspsdj2gv6vl8six5\n" +
        "5gctkjzxlr2twoseventhree\n" +
        "rmgmkvqeightpfmrxqmvkg8\n" +
        "3sixnjrjbbzl3\n" +
        "1nineseven4three7qhdsxvbmlk\n" +
        "fourjbznsbgsn2pgxrzlkkjtctm3eight5\n" +
        "36fourninecppsqfflbcbljnfgh2\n" +
        "eight211ninegnfvhfxqcmpmeight\n" +
        "vbsg73\n" +
        "3ninetwoonerbzcglkmdg\n" +
        "76ngkrtfonecltwovvgvgznzbmxm\n" +
        "977eighteightwocp\n" +
        "fxskxcdkdeight2225\n" +
        "seven98rpzjxscseven3vtbbhqjrjfk\n" +
        "sevenseven97jxh\n" +
        "sevenfourfivexsspnqjnlxtbrfour24\n" +
        "fivefive5two91six\n" +
        "gg2ptrsdxtfjtzztthree8\n" +
        "eight2ncmps1qsix25\n" +
        "eight486zfqfmgchtrrbcrjsevenrcqtxnqnrb\n" +
        "7vgn31lvqqvkdqlpddmllbn9\n" +
        "1hlgrlmctseveneight9xfsfseven\n" +
        "onefourdqzvlh7\n" +
        "four543ninethree\n" +
        "4seven1one\n" +
        "79twogmjcngj7rseven3\n" +
        "xxtkcbkgqfldssix4five4nine\n" +
        "tqxnnspd7sevenvljzl2scsbkhqdq\n" +
        "cbz3rczscjfxtzfivenbjqone\n" +
        "threekkcjlmvkfrsgz6r\n" +
        "1sixvppcksdvrz7\n" +
        "dvngzs74eight9\n" +
        "qrncqtqxkfrndcrrpjcglfonesix75seven\n" +
        "eight6cksxfdthreefive2eight\n" +
        "four51sixfschln6\n" +
        "hblmcggzgqsix2two\n" +
        "93two985\n" +
        "78six6\n" +
        "6sxmd289nine152\n" +
        "gmpdcdcr4xzmhq3\n" +
        "5threehpdmq\n" +
        "eight54xcrlsv8three4\n" +
        "35twofourfivenine4tjthd\n" +
        "6kch9\n" +
        "7fjlvptwo2ztrggpmsntwo\n" +
        "7twosix6kmdnvspnqgjxcdtgrspjj7\n" +
        "tsix8fivethree\n" +
        "2pggbgxnft7\n" +
        "sixthree69j\n" +
        "24l\n" +
        "cpzltvslq9nfhcv\n" +
        "six46eightsixsixbblvjjkvntmm\n" +
        "7five3\n" +
        "six2three\n" +
        "seven2xxxhhjnl53sixjtgbnvh6\n" +
        "fiveeightj1mrfvzfour3p\n" +
        "6foureight588zpjdcxlrshtwonine\n" +
        "xvtwonesix7prcjfsxjksknxqqsmsix\n" +
        "eight3fivexmrs1eightnc\n" +
        "vczdhchhsmlx7zdlcgfzrcgkcnqdvdtphxqqjxnsbd\n" +
        "six2fxqqdtrkgqpgjrvhxtsbqzz\n" +
        "twotwofour4six\n" +
        "9nzcvxthree\n" +
        "kggfkpvhrronep238nine\n" +
        "41seven4sevenfourvrmxkhpcmskbctwo\n" +
        "nbttnvh8nlhldjstkvdxxlvqeightoneights\n" +
        "tjqdkfourthree466\n" +
        "twothbcvstwotwo2xpnqrldsmdtscnrp\n" +
        "sevennine3\n" +
        "twodhbtlnzrt418dlszqkbc78\n" +
        "3four8threeonetwoneh\n" +
        "drtcjpmrlnine3vgf8kssrsssgpnseven\n" +
        "eight78jqjjkgtbcckdndhdvz57q\n" +
        "five59onesixsevenflls\n" +
        "63bbznssjjsvt4\n" +
        "fqkgmcrxf6gkcninesevennfzhccqtfour9\n" +
        "5nine2three\n" +
        "gfkhpkfgb9four49rqcjrjkglpzxr\n" +
        "ds28eight33xl\n" +
        "qdgnn9ninecpcv\n" +
        "2sevenrlfkzmktzgsevenzzgxfrmp\n" +
        "twovpthxmxqgr94\n" +
        "sk3gbmrknrmm\n" +
        "7sevenrpxjvzeightsix\n" +
        "9zxzqglvxqm6jphmvfsqvjjqsl\n" +
        "9kqmnkthcdhtwovbrqzftst3\n" +
        "eight669zvrdpv\n" +
        "shgjkgthreeznz69pjltseven\n" +
        "ninebc5eight\n" +
        "5l\n" +
        "onesix5five2clxllfour\n" +
        "71three2fivecplsnlgsmthree\n" +
        "twofourone6fm7four26eightwox\n" +
        "7three9ftpvvbzpjzsixssxbqcfsix4\n" +
        "92eightlsgrmpqtpptxrdfxthreemvlxfpsevenoneightdd\n" +
        "eight7three\n" +
        "drxxcghbsevenninenineljtczntp6\n" +
        "nine55cpqfkdrthree3\n" +
        "7fivefp3eight\n" +
        "97nine1ninexprdpvqzps\n" +
        "four3eightpgbdhnmqvhjjhg6frqkpqzbtwoner\n" +
        "3threefivesevenrvr3sixthree\n" +
        "sixs6zl184\n" +
        "fourlfkxcvqkllbtz45threefivesix\n" +
        "2twodvklqcqdjjdnpx84xgthree4\n" +
        "eightfour8dnqmlqmxd9cmt8\n" +
        "t4sixkkfhgmn83eight\n" +
        "eightoneninehqddxnine75vppqhlcm\n" +
        "1threesdvsszeight5dcsgrsv\n" +
        "seven776smjhhb\n" +
        "onevmr62dqzt7\n" +
        "pqxtspl19threesevenkjvxjdhxkseven\n" +
        "cgkvmx5lffclxgtsnseven\n" +
        "fqjctfrrlmmnpeightone19nineqgsnsqbjk\n" +
        "8twoone\n" +
        "c6eightonep3gxjnsjtwo3\n" +
        "sixthree36sevenseven\n" +
        "5vgfsdkzbxmvxncxjpsxffcbnr62kmgmhcmkq\n" +
        "nineeightfour9kvdmxg5nnhrf\n" +
        "5blqszh97fhgpbdn44\n" +
        "nhzbqprgptnineflxgvfkvlp453two\n" +
        "kpcqvjcjcj6dfpsljlrxdlzbf8grsnsdmklp\n" +
        "1zkjbnln\n" +
        "four2xvxrrvs\n" +
        "nine5nfmbxnrgfnine8onekqcnine\n" +
        "oneonedd8\n" +
        "rr44\n" +
        "8bckneightnqmkvqhkkmxfour\n" +
        "2pznjcxlj4onenine433\n" +
        "nhmhkcqbsrrthreeeighttwo3f5\n" +
        "eight64sixninefivethreecfbbdk\n" +
        "csmoneight1hrsevenfivesevenone756\n" +
        "9qdrxl\n" +
        "26two3jq\n" +
        "pnrskrrvtonesevenrmkcxcm2five8five\n" +
        "sfvfr8three69three7fs\n" +
        "seven52bkslnnfrbqvmblknq3f4\n" +
        "zqmtdtp31threesevennine3\n" +
        "9tbvvjstzmdpqnpbmrb32cbdjgtsjndjrps3ckpmspm\n" +
        "5four4rvmtkppghb9\n" +
        "24ftjxbdq3nine\n" +
        "ltj2oneeightonesix\n" +
        "76three2sevennine\n" +
        "hfnzxcjfxgseven5cpph3\n" +
        "2one966dpjlgfqbmceightthreenine\n" +
        "5one9smzz76eight\n" +
        "348tworhzvqjdmqtwo\n" +
        "cjsvvksgzkktwo7hsfkrhkcsbrqcnrz26\n" +
        "threethreez8\n" +
        "m3335cdgbxqn5twodmcqk\n" +
        "27eight4\n" +
        "sfmspqbzr9eight\n" +
        "rscxzq2fqlhbbhvkdbzqzqhzfourninepclrkkdrtwosix\n" +
        "pxbld2twonef\n" +
        "plpbbkvxqpvdxqcstp5threevljjqsqxsevenseven\n" +
        "2sevensix9\n" +
        "5413sxmtrdjtcmdqpbpcprsix\n" +
        "tpdqxscxjldqvzncbvrpr9cvkqdffvfh8four\n" +
        "six14\n" +
        "nsmqttrbhrznvonecmlxtdclnbk3\n" +
        "ninecgbqh6twoctsixthreefive\n" +
        "hqsgonesix3oneightklm\n" +
        "cxxbjptkvkcttddmtwo37one5\n" +
        "v13two\n" +
        "txxm84kmrpdkxhtbntkhj4four5\n" +
        "jsrzgnine8nrmzpgf5sqdz\n" +
        "4six9dkxttsthreedgvjkqpk\n" +
        "msnrq7\n" +
        "t2five4vtwo7sevenrjdrzvb\n" +
        "2rxbdzlszjseven7\n" +
        "gmmninesix3119ninemdnprsmd\n" +
        "ninesevenpbfx6fourfivefdvhrsctztrheight\n" +
        "qk3two317hnpkqxbmkb3\n" +
        "oneone6sixdzdmfonefiveone\n" +
        "427sixfive\n" +
        "17njgbgljkpxvhph\n" +
        "4hnfvpbvzxl6three\n" +
        "5sixnllvrvpjpv\n" +
        "3sevenfzjltglsjkdknfnmpsvfive6xdsm2\n" +
        "1pxp8onesix\n" +
        "xclcfthreeln9ndqhvdxknkjzv4\n" +
        "6fourtwo2seven1fcd\n" +
        "1eightseven4\n" +
        "four21eightlfjzb\n" +
        "nine9ninenine81\n" +
        "eight8zpfsshlqbdlfourmch5four\n" +
        "6sixjdmjjgmsk\n" +
        "ninesix8threetwoxtqdsffxlk6\n" +
        "dgsddfcnnc3sevenseven532one\n" +
        "lsevennineninefive851dtqzv\n" +
        "nmrxfsmfcscftvzzbggglsfour6\n" +
        "threesmxqlgmpvtwokvrx361eight\n" +
        "brbkgqcblcxghjp34bpnrctz\n" +
        "sixbzxfbfsjth14pqpvjqfmr\n" +
        "oneseven99\n" +
        "7four6562zjjxxjlvfdqbssmcx\n" +
        "8fjssqgzthree4five3\n" +
        "fourckmtsssqgdgcvmqhcqlcqqdhv5eight\n" +
        "bphtzndpdrfivefour8nine5\n" +
        "ninesix57jvjtwo36vzljdfnndv\n" +
        "eightfourfivesixone2vg\n" +
        "5sevenkdgcmjthdxpxprcdnzpffsixcjmh2\n" +
        "9cvldprttjk1\n" +
        "seven6fivesfjjshfqmsjvfpc\n" +
        "eightsixstmhlldl21fourvgsmdlcd1\n" +
        "5nv1two\n" +
        "tsqxlfnd6rtcvcv5\n" +
        "eight3zdljlvkbp7hfive5xzgzspsnfour\n" +
        "945sevennrtnn57\n" +
        "562\n" +
        "3vtnlsfoursjbgbqmlx6\n" +
        "8lprsrtvrh9two3\n" +
        "pssfncbhqpfour1dgcjqpccfzfntphmtjthree1sixfour\n" +
        "rchfmfp18998rsbx\n" +
        "nineonedmlffz5\n" +
        "seven2sevenonetwo\n" +
        "nine3gxttrkkzpj933mjzhphl\n" +
        "cdpqqhrcrrnspsr378two\n" +
        "fourrprdlkvqj8tntfttwofivesevenqmcsgpljvnl\n" +
        "978sixskr2gkrcgn\n" +
        "jcvldmcdqbjdcxhjcgngsevenfive2cfcmbb4\n" +
        "szlsvrzzkseventwoone6ninesevensj\n" +
        "gzboneightmsblxgzmsq5seven\n" +
        "seven5eight5\n" +
        "tsblj5onebkx882\n" +
        "7kdgdfvx3sevenczgf\n" +
        "94g14onenine\n" +
        "7fournrkdxz4threethree\n" +
        "8eightqtworlcxtv4\n" +
        "rbkbdsqbfour39eighteightwoxn\n" +
        "cxgmxtoneninennqtmzml6dq\n" +
        "8fivefour9\n" +
        "8bhspzfsjr9\n" +
        "fivekzgvvfour8sevensix4vlphpblsp\n" +
        "six63kbbxrfivefive5\n" +
        "eight5gmkrhrkjjxhb\n" +
        "xtcfivepntwoeight9seven\n" +
        "6nine8fivenine2mf\n" +
        "5fourbthreenineslxfgtqrxcv5four\n" +
        "4vhkxmlsvfg\n" +
        "scphnsbz9h6qnlhcqmgl\n" +
        "tbbcqfxrllszbseventwofivethreeninef1\n" +
        "zkvtlscldhngtk59\n" +
        "one6fourrmftxfsvmtwo874\n" +
        "37threeonefive4\n" +
        "lrnnspbrgd6jzxtbninesevenngnpsljcr\n" +
        "xhldmfc4five76five\n" +
        "qrzfivexklqcjdnine46\n" +
        "jkgb6ninesix41threeseven\n" +
        "134628twozlm\n" +
        "8ffrzgtbbfgfive2ninethreem\n" +
        "2132\n" +
        "7xf\n" +
        "mfhmshvfivenfzjhslq7nfcfgvjhs8\n" +
        "seven3248\n" +
        "pvpdpxpg135seven9vpcpgrzlpjblmd\n" +
        "shnslhthreefourtwodnpfr7seven\n" +
        "6hxhhmfivesixseven\n" +
        "vppgmfivethreefivesevensix2two\n" +
        "hp98\n" +
        "phlskgmgrjsbtq2gkjvrgsd\n" +
        "kkfourthree9fhnpdqcqhtwo\n" +
        "ftnvkprhvllkh9n\n" +
        "71one7twofourfourqtfmc6\n" +
        "eightfivehssmqsptconefive4\n" +
        "ninejcfqknhcfpcbcsmnpvn4six5j\n" +
        "one7jvmtxkjzfive\n" +
        "twof9pqcgdfqsq4d7\n" +
        "krczdrpxbhsngqdvsqb1four7mb7lldv\n" +
        "seven9634tgcsplgmfivetwo\n" +
        "vjvpstpbgtsevennvpsvch97rslh4onefour\n" +
        "zbtgjgq23seven7lbnzdpnkzf\n" +
        "zndbhclr714\n" +
        "twofive3\n" +
        "9eight2twojxzdkptwo\n" +
        "gzqfcqpxnfhtb28dvfeight38\n" +
        "rsqvgsqv9tdlvssj\n" +
        "f78hjftphgcv8bqgrckgldone\n" +
        "fivethreetjg2\n" +
        "6vtqgdkxsmj\n" +
        "xgjdndnpsevenzfl6tfgxltvcthree\n" +
        "threenine82gqnffkvm\n" +
        "zmlblc4fiveseven3two\n" +
        "msmlvbnqbt9\n" +
        "144bfcbsjztmdldveight\n" +
        "chceightwofivemcfrxv266\n" +
        "two9f7gzhhsf6\n" +
        "ninetwoffour8sevenjngv\n" +
        "foureight22g7twoonemlvq\n" +
        "one78ptfgbbvx\n" +
        "fx5\n" +
        "5rvz2two\n" +
        "913\n" +
        "9eightnkvhcksoneqsqgntfthdtjm\n" +
        "one1sixcsccdvbxzx\n" +
        "sevenoneninethree4one7seven2\n" +
        "jqseightwockmxjd3gfmlhbn6seven7sevenkhcr\n" +
        "sevenqqhs4onemcn\n" +
        "fourseven3nine7pcn\n" +
        "sjjpsthkdfeightcsvlcvhltv6\n" +
        "qpc16five\n" +
        "3jplhrj2threetwofpvrthree\n" +
        "4sixsix9two\n" +
        "one1eighteight\n" +
        "5tg\n" +
        "256five9\n" +
        "seven9crnff9eighteight\n" +
        "16five1one4kqllsltrtn\n" +
        "eight3three\n" +
        "seventwoqtlxj8\n" +
        "74seven5\n" +
        "2five7mmgsbfc\n" +
        "five7four\n" +
        "bmtkcxvcj997eight\n" +
        "cpgrpgxtgkqr9\n" +
        "sevenmdqtqhfvnknine929xm\n" +
        "nsix27vzglsevenseven63\n" +
        "six1nqpsgtrllsnhmbnqxrdvrcx8s\n" +
        "eighttwoflrvzfq262\n" +
        "twosxtf866hfhxn4fourone\n" +
        "3fourzbrtmd47three\n" +
        "four99eightbcldqfvrm\n" +
        "871\n" +
        "2twobdtnzzqgvfggjntvgpnqslbdctppnfzpfpcbvzqccq\n" +
        "sdmkzhb8lnpjntj7\n" +
        "threembr1\n" +
        "5fd1sevenpsdpdlnb16\n" +
        "7mnkkvpzrrnslfksrninexmpnfpbzhkx\n" +
        "nfrnvtt8\n" +
        "24dsffiveqzmjrjznfksrknrfn\n" +
        "5foureight3pn3\n" +
        "nine9three\n" +
        "nine74cmxrdvcxf3pdhbfour\n" +
        "frjnzrsixone53eight\n" +
        "four41fourhfjnjhpkzp\n" +
        "939rdjhlfpjsix\n" +
        "4kdkcq9two\n" +
        "329fivefive98\n" +
        "65485\n" +
        "dfsevensixmdbfour7jhxsfourfour\n" +
        "rqtwonerdkf3eight6fourfour\n" +
        "twoqnfthree5fx\n" +
        "rtwone1two89ntwo9\n" +
        "sixskqssbccfour7fivevcmsevendqbfcvks\n" +
        "sgtwovmzmzm9\n" +
        "vk9\n" +
        "seventhree4\n" +
        "48mv3eightnine\n" +
        "six7gxnj4six3\n" +
        "twotwosixlm55dmzdrntzthreeseven\n" +
        "fivemhcdlm8fivemkffllv9\n" +
        "fkxzdh69twoonesbrfhntk\n" +
        "zfourthreeseven1kllk\n" +
        "6ninethreefiveqdct\n" +
        "nineeight136three5nxvj\n" +
        "fivecpbkhqxpmf46twotxtfrhmvboneone\n" +
        "brrfqninetwohgqnkfctkseven1\n" +
        "npblhpcpfivehdsnine34\n" +
        "vksix4fourvrbfmjcrhb78\n" +
        "72xfmds46threefive\n" +
        "five1kq8eight56three\n" +
        "3sevenfvcsglnjtbhdkqf\n" +
        "6tr6qxqrmstqg\n" +
        "15five5\n" +
        "fthfvffour85\n" +
        "seven81fouronefive\n" +
        "dhkknlbfjrnsfcvvkk9seveneightwos\n" +
        "2lngrlvrk4shgktcbpfonefivenine2\n" +
        "sevenhhlrfqmzn2\n" +
        "6seven927gdczblhjlmrxnjqfktwoneq\n" +
        "7phbj9fourvbx31seven6\n" +
        "146\n" +
        "jnqxslzpsxdftrqczq764\n" +
        "tmbjdldtwogfvxhnvsfp8tzzp\n" +
        "fourgv68bblxfktsfdg98\n" +
        "36tnrmd2jrllk2npbrctjcjthm\n" +
        "mx3nine3hkslkb5\n" +
        "xvmgtlzmrfjcmqgtworc3\n" +
        "vxscrns1lclnxtwo\n" +
        "foursevenone534\n" +
        "jdmrj1sixkzdxn\n" +
        "two9threenine\n" +
        "2sevendsmlzh13jlslmvtnine\n" +
        "nine8nine\n" +
        "gthbsq953kxckzppcxqzl3\n" +
        "xnrgzjzrbp5rptrpbsdgsqfeight5\n" +
        "1sevendnmxkpdsrmrfkpmxcq22sixmdmvqlgpnbcxf\n" +
        "eight658x14fq\n" +
        "rzvgmdltnz9nvthrjvpzqf\n" +
        "9oneightgl\n" +
        "dsbtb88\n" +
        "three4fourninelzvqhvjpk6\n" +
        "seven59fourthreed\n" +
        "3671\n" +
        "66nineeight8two\n" +
        "eightlszxlsxlcq3sixskqhj4gkblpj\n" +
        "three2eighttwothree\n" +
        "nine853qttjrjptxttwortkhmjss\n" +
        "twosix35\n" +
        "5948lspjxzpbmthfive\n" +
        "fourthree8\n" +
        "fourfivevbbqpppqrkkzjqqbnine3\n" +
        "8nine4xszllqzzonesix2nine\n" +
        "crgnbqrfourrzjbpnnsqthreethreefbnine85\n" +
        "dx79xjkcpxsndsrbnjlbnine2\n" +
        "9nine89\n" +
        "one7qmv1\n" +
        "dlpbzxfm536392fp\n" +
        "3seventhree8eighttwoeightfive\n" +
        "twongjrfkcb66\n" +
        "2eightseven8\n" +
        "zffrln57eighttbqsgzbzhrzxt5kxxlcxb\n" +
        "one5three621ninetwonnprsbmm\n" +
        "3vmslzzp8xcpcgvf\n" +
        "threesix93\n" +
        "seven3sixfnbbbeighttwo1fivezglzb\n" +
        "kgk7\n" +
        "48seven2ccztcfnv5tzkrxffour\n" +
        "xczvzdjthreeeight6hnffivexxtmqs79\n" +
        "three4nine36threehjp\n" +
        "nineqtdtmmpjpkzpxmmfive83sevenseventhree\n" +
        "22jfdpndrcvxbgz\n" +
        "7bljfctkbpc\n" +
        "4bfblqrphseven\n" +
        "fklxmcqxthmnvrlc9\n" +
        "4seven9zspgftgvd53dsdkhgbns46\n" +
        "7seven664fdqkcqtr9\n" +
        "dvxtkqfqbhrllbone3six3\n" +
        "4ktplgtgzlf3eightfxslssr\n" +
        "six2bhsjknjmgdddgnb6tbhvxbf29nine\n" +
        "two93twofngr8four\n" +
        "oneoneftmqvblcrjnng7jvch97one\n" +
        "9fivexmzstmlrmztwohsqmzfivehseven\n" +
        "5two2hggzchnn\n" +
        "one28ptdlfourgnrjftqd4vxfdrfx7\n" +
        "six6zvkcszt4tfpkeightvdkjzbb\n" +
        "7oneftjp\n" +
        "1sevenseven9fsp\n" +
        "jqtznvrq8one11fivesix\n" +
        "3ninedkqxtmoneighthkt\n" +
        "8k\n" +
        "931\n" +
        "clhvprlljttm9\n" +
        "four14bfgf4eightwoc\n" +
        "xrflnnfb2rlv7twoseven2six\n" +
        "6366hlgklvjvxxlbkxgb\n" +
        "nbkxvp3eightgnznqqjbt5seven\n" +
        "98sntdts\n" +
        "cneightwotdkfxxxjfdpz3zkkthree\n" +
        "five1sfhq1lhhvjb\n" +
        "zdd56tcdchkvnbn\n" +
        "sevenhtpbmbntfivethree9scjfivenine\n" +
        "2spxggcvsvm4msdszqtml\n" +
        "4twoxsevencjgnine\n" +
        "89eightonetwo3ghqbckqkn\n" +
        "fvsgljnzgzfive1slhbxxhsrlmfivexqnkmtnzx\n" +
        "1g1\n" +
        "94mcreight\n" +
        "threefntlsvvfnine9\n" +
        "b3hnhvjhtrrv\n" +
        "11fourthree46\n" +
        "plhclxcjrsgspx3b8fivecbx\n" +
        "mvjxqnqxtwo89bfive\n" +
        "three9nkjrh6two3\n" +
        "dgprgjdgcrtqxgvknnk9six\n" +
        "dmbljtqg66zxjr95nine2seven\n" +
        "vdxoneight6\n" +
        "22two9\n" +
        "7oneppgrjnmrvchvsznsgfivexxdt7\n" +
        "1three4mzc\n" +
        "bdnhvtsjmdnklsxbtmnztqjtpnz6fivesevenfourzddgsrfmlq\n" +
        "krzm2twotwo65sixfhpplvcgcs\n" +
        "qzcvbvsfive1oneqzc9threesevenseven\n" +
        "threesixninekghkvvzd4\n" +
        "txqjpmlvdlpm7\n" +
        "eightsix1l96xrljgg\n" +
        "two63d32six\n" +
        "8nine1fivesixfive3eightwos\n" +
        "sixninenkrpsix2nf4\n" +
        "four2seven35four9threensbv\n" +
        "ncjhcskrx6\n" +
        "3eightcpssngjlsqvmsxqqpldhsxsthreelzgzn\n" +
        "6zjnmxrgcz\n" +
        "9bbvkvnbmzshtdzxgqnqmqtthree\n" +
        "four2kqmzfgvpk35rhmqhtrqmfourhjxxfour\n" +
        "9eightfivefrpqtzmkkgkvjbbqmsqvq\n" +
        "eightsevenzpskfbrmcgzjjpnlgr51bdlcmsxhf\n" +
        "pt8two6seveneightjsqxjmlf4six\n" +
        "phjclrmpzm1292gdfivenine\n" +
        "sixfourtwo1\n" +
        "9tvcnzknine2rdnqfive81\n" +
        "sixtwopvxjcnmone2kxzxgmn\n" +
        "twosixpcntbtfivenine4two\n" +
        "rxdgeightone86twobzmnlgkdc\n" +
        "4two1twovtldl8one\n" +
        "fiveb1\n" +
        "212three6twofour84\n" +
        "74tstlfmrmcj\n" +
        "sixgxtwotmrmzkfsj9\n" +
        "eighthksxmf144xltwo8\n" +
        "mthjxjhnqxnhcbxg783\n" +
        "prptwonehhdlrd71threeone\n" +
        "59fivefnsmzfsix\n" +
        "ninesixonetwo9six6jtptone\n" +
        "eight9ninefivezqvpstsevenjvcjmdcscnzlqsfnhnrnmn\n" +
        "2ckgjml4rcprzj7tp6\n" +
        "sevenfivesevennhg136\n" +
        "ninesevenvhl5\n" +
        "fzflrseven1five5seven\n" +
        "seven5lcfxp\n" +
        "bqhjg4three3\n" +
        "three8ninegtonetwo46\n" +
        "cvdpr8\n" +
        "32fivehfsdhxgjnn\n" +
        "sdndcpccpvdzdgn9fourlnslcmbtwojphzpnvrnp\n" +
        "9cqkgdf7fxgdfcllvnnmzpptninesixone9\n" +
        "3chllzcgq5fivebffm9\n" +
        "sqmtj4qlhlcrmrnb38v4dsix\n" +
        "sevennine84bcpvqjcrxpvtcgfhlfhncplktf\n" +
        "qkzxvstdgnfour4two\n" +
        "jkhoneonesixfiveone14lvzn\n" +
        "threethreefivensvlbfour2four\n" +
        "vgqlhqfrlfourlzcgppdbhq57\n" +
        "bqzpzbtwolprtwo9\n" +
        "lfjs9six1five2fzcldvnpxtmhsix\n" +
        "kslcntz36nine\n" +
        "nineseven8rzccgfhzsjnjveighttwo\n" +
        "three3fourfivedmjlgqfhmninemst8\n" +
        "4qxvzgfvctwo73\n" +
        "75961fivefourzg\n" +
        "spcbt66sevennine4four\n" +
        "hhb1\n" +
        "dtmoneight9\n" +
        "3mbctjhfmr2fourthreeseven86\n" +
        "sixjsbmvzql6gfnttq\n" +
        "1vknfgmznmnzpgvsp3bsksdsevenfourrk\n" +
        "six4six7ninepfxjsshthree\n" +
        "4rqgzpnqcg8skfgksjone3four8\n" +
        "seven5zkljftwo\n" +
        "76sctscqtsfcninefourrgmsbsxv9six\n" +
        "46fpdqhkfjzgtclfchbbsjcbjhsbkqggzhlb6four\n" +
        "bshbvfourzc79lvvdsqjksmzmqpbvrsrbtg7\n" +
        "jdqmtfeight59fourtwo\n" +
        "ninefivejsl3\n" +
        "94z7fouroneeight\n" +
        "5nbmvgheightfive\n" +
        "sixseven5one9ngk3\n" +
        "eight3jddmgqnzcfjsvrd6five6kmbxss\n" +
        "seveneight9fourthree\n" +
        "eight83\n" +
        "3spltxvtbg\n" +
        "92shzldthreefpckdtqhm7fivezzkdlz\n" +
        "6two9threeztrzxphhksqc\n" +
        "ninedlone3\n" +
        "eight4nineonefournsmdgkdszt\n" +
        "9cpxhnksktwo15fivefkq\n" +
        "144eight77\n" +
        "1sixjscflltdrgclmgrszdfive7lc\n" +
        "ttmfsx9dzgcqjzlzhvlfqrsj4six\n" +
        "846\n" +
        "fiveseven7\n" +
        "kqtwone2ninefour7fghmntkn\n" +
        "8r8one\n" +
        "5nnzqqgxl4gbgnzntfrhqzeight\n" +
        "onevpkxvrone8\n" +
        "79klfd\n" +
        "gzrjvck1sixqnfdjxfive9eightcmhmsjpl\n" +
        "nszqhdfsixsixb3threenfiveqskccbffd\n" +
        "srbn928eight\n" +
        "eight2eightfivekmnjkndgrhjdpvxk3\n" +
        "9four11oneeight\n" +
        "seven6fivezzktmsixv\n" +
        "fivebvtnzr4threeonetld68\n" +
        "mgbfjcjbqctt71fgdbmmqdlhpxnpmvx\n" +
        "rjprxbxrfk233\n" +
        "nxbjxbcvvskeightfiveglpnhbzz27four\n" +
        "kstwo2\n" +
        "2btbzfournbfcxnvlvcbsjmplnprcrg\n" +
        "mkk6three271\n" +
        "tfncrvlnfdmntdrmjqqtknsgpq671onethree\n" +
        "eight8twofivex\n" +
        "phreightfive81hftbkbdnztt\n" +
        "onetbhqqlcbqrlfzrqbtbl9ntcgvxr1rhgrspqkgklz\n" +
        "gckbonekhzcjhdb5\n" +
        "twothree1lfivetwolpdxhn8\n" +
        "threebqmxgpjfbzrrrrgdt8\n" +
        "threejvlpxpfm9four4threeone\n" +
        "five68onesevennineone9two\n" +
        "mjqjrqmeight73\n" +
        "fvfgrdppszgdhmninenineone7759\n" +
        "lrhchsonek3twobblvn9bdmcbt\n" +
        "mdcqxbz84five6ninetwonergj\n" +
        "eightnine548ttfiveeight7\n" +
        "74mfftzxhkl4\n" +
        "seven5mdmrxlp\n" +
        "ptb76ndfpbtljpkhjthdfmsdddjssm\n" +
        "7vkeight\n" +
        "bzzpvht5fourthreeseven8\n" +
        "rztztsix12nine\n" +
        "fvpqdnphtd1mmrhppbd2\n" +
        "h8dpbvs2tjlqgfxhhbeight\n" +
        "51one\n" +
        "two86\n" +
        "sixnine7sixseventwo34\n" +
        "two45xjcpcnhgbsb1five7\n" +
        "qqkzvpsixfivepfzdhtl92six4rhp\n" +
        "two6vqtxvxrvzpz\n" +
        "1qqsfrgdbsm8five\n" +
        "threeeightsix36xvtm\n" +
        "nine5eightczhsix3twoprztckvb\n" +
        "pxrsgpszonepdjvxcblqzkr61seven11\n" +
        "5sevenonesevensix4six1dvhrx\n" +
        "cdxnbseven9qsevenvbv4\n" +
        "sixlgjt3\n" +
        "dhpxhpbkq3lc6rkjlpdz4five5pctfzsplrf\n" +
        "1kmsmgjpmkqfckr\n" +
        "sixeight1k44\n" +
        "52qdfp1b8\n" +
        "86fourthree42\n" +
        "six2fourpjtsvskrxtmgxnj2one3dn\n" +
        "rjtfqxvfm88seventhreeeighttwo\n" +
        "fivepgfvxcds64sevenhg\n" +
        "glvhcrgbtphxfsfourthreerqhjxpzone5gh\n" +
        "1sevenone34\n" +
        "689five9ninetwotwo4\n" +
        "6two92sixjb1cbhmrq\n" +
        "fiverrvllhbgcsskh2\n" +
        "foureight6fhtx1five8eight\n" +
        "pqvvjkhtxkxcjkrf9mn\n" +
        "threefive2hs6one6jhkbdh\n" +
        "twoninefzflrqqzvp2xnr8\n" +
        "one51\n" +
        "7bjpnfsgpszrfk5fourthreebvvn\n" +
        "six74\n" +
        "twozcgbrrhxcpznx9dlcgdchpndcdc\n" +
        "nines566\n" +
        "one72zshxlsix\n" +
        "vseven4fouronenine6\n" +
        "7four1nine2threekzjbs4\n" +
        "onecq3four\n" +
        "twodcrx8\n" +
        "four35sjjhpfftzsixfqctsfonefiveseven\n" +
        "sxqnssjtwothree2\n" +
        "8fdpjrztwoseventwo5rmqvoneeight\n" +
        "pjlbnl3rg3shchseven\n" +
        "zdcrnpddv2\n" +
        "eight2foureighttgjcxtf2\n" +
        "ghhxlxqttvonerh96715twonectr\n" +
        "9hmfxxrsdbsixbtwo7sevensix\n" +
        "32ghjqjfp7three4one\n" +
        "197\n" +
        "twon8five2\n" +
        "vtwobrlhqsq1twothreesixthree\n" +
        "xbdxninefour8seven\n" +
        "five39\n" +
        "621eightsix\n" +
        "21fvdd11tsdzhjspzld4\n" +
        "7seventwoeightfpnkhxmvc\n" +
        "96sjrcvzxsevenfqt4seven9\n" +
        "xzxmtsrhbfivenineninerxgcrx9one\n" +
        "5pzgmrgrg2kdgl9one\n" +
        "lqzmttxcpp7cnfstnhtglzhssntjmsixseven6six\n" +
        "two711\n" +
        "6onevjnvmkkx\n" +
        "eight7dbmznvztwo\n" +
        "9mlpltkt3\n" +
        "7ninenine4tpjbsbtsgzttlgrtnfvr91four\n" +
        "foursevenq7\n" +
        "six1sgtbsmgft9\n" +
        "nineone28fourjtwo8\n" +
        "76threebgqvh6lfbkdmfvcthreeone3\n" +
        "13cvtpqnmbv\n" +
        "1sevenzjhtfpbfb73rccvtnmtthree7\n" +
        "4xhvshhtmxx7sevenf9\n" +
        "8one1\n" +
        "931fivetmdmsrrmfxrplkfvfourthreeeight\n" +
        "qzbthffhlg2\n" +
        "one4eight33\n" +
        "qfjqt9jlcthreeqkfdpfiveeight8scfnlj\n" +
        "fvczqbtsix2bxkgsnsix5nine7\n" +
        "9qxnvlnine2phnlqzninefive\n" +
        "tszjsxbsixtwoeight62ffjtdnxxtwofive\n" +
        "one2skxg\n" +
        "five5onexzgzkjvtqrfourfive\n" +
        "twozsxzqtrqbxqqqsbcvfpgdcdpttwo1six\n" +
        "8mqkgptxsixhqmbqshcl\n" +
        "lsdlsxrhdqthreesix2sevenchjxvmsjpvrnpcblgmsix\n" +
        "gngrfrhbxhqkxs5fourr8three4\n" +
        "jlzszzz9one\n" +
        "twozrbjkjpzseventwonine8dbmfdjcb\n" +
        "3nine36ppqone4czxvkxjzv\n" +
        "ld6eightseven6twosix\n" +
        "1jnbfive\n" +
        "7threeglmcdhpvq4723fivethree\n" +
        "seven148oneightd\n" +
        "sevensevenseven6sixtwosix21\n" +
        "8twojhdkdrcqgmclqlldv6sevenonedjthcz\n" +
        "ninesevenggsjbpt5ttlrq\n" +
        "59sixfivefive\n" +
        "eight9bsmcgkseventhree66qmgpkkxnpm\n" +
        "fourthree73fiveseven\n" +
        "9five9six8threet\n" +
        "3eight44\n" +
        "dlcbjflsix5ttvjdxzzeightcffrtfjcjpxtwostrdc\n" +
        "fiveone645fivellfcmqqmnine\n" +
        "hxdtshfive115tfvrzqhgftwojtjrcshgtq\n" +
        "6nqrfrhv17jdxpfmmdt4five\n" +
        "sevenxtpjxnrr1\n" +
        "krzkthreegjnqrfbsdrkqptd33rsvrzvvffqhreight\n" +
        "472ggfive56hgnvz\n" +
        "12tkpchqtnine\n" +
        "vdbsctv6eightth82\n" +
        "fivetngxlttf4\n" +
        "5nss\n" +
        "5onesixsevenphxtmlqhzfcjxrknpv\n" +
        "gldsixrhss186seven6\n" +
        "gnpksz4\n" +
        "4919\n" +
        "pbc19\n"
fun day1partA (input: String){
    println(input)

    var lines = input.lines()
    println(lines)

    var numbers = lines
        .map { characters -> characters.filter { it.isDigit() } }
        .filter { string -> string.isNotEmpty() }
    println(numbers)


    var calibrationValues = numbers.map { number -> numberToCalibration(number)}
    println(calibrationValues)

    var result = calibrationValues.sum();
    println(result)
}

fun numberToCalibration(number: String): Int {
return (number.first().toString() + number.last().toString()).toInt()
}
